### ISSUE TITLE
怎么没有建表语句呢

### ISSUE THREAD

**Issue by shenzhuan** [GongDexing/elasticsearch-mysql#1]
怎么没有建表语句呢

**Comment by GongDexing** [comment]
@shenzhuan 将mysql数据同步到elasticsearch这种场景不要建表，mysql里面肯定有数据了，不过，你可以说说你们的场景

**Comment by shenzhuan** [comment]
我是说mysql的表都没有，但是现在代码报错了  好像是包邮问题吧 qq 1439226817

**Comment by GongDexing** [comment]
@shenzhuan  可以把报错的日志贴出来看看
